---
title: Memulai Bisnis Startup
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tag_text: Wujudkan ide bisnis startup anda sekarang juga.
description: Startup adalah usaha rintisan yang sebagian besar berbasis teknologi.
  Istilah startup mulai populer 10 tahun terakhir dengan mulai berkembangnya perusahaan-perusahaan
  teknologi rintisan seperti facebook, google, dan instagram menguasai pasar.
url: http://www.rocktokom.co
baseurl: ''
excerpt_separator: "<!--more-->"
font-awesome-include: true
markdown: kramdown
paginate: 5
paginate_path: '/blog/page:num'
gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
  - jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
